config/routes.rb
Rails.application.routes.draw do
  resources :short_urls, only: [:new, :create, :show]
  get "#{ENV['REDIRECT_PATH']}/:slug", to: "redirects#show"
end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
  validates :url, presence: true
  before_save :prepend_http

  def shorten
    ENV['BASE_URL'] + ENV['PORT'] + ENV['REDIRECT_PATH'] + "/" + encode_slug
  end

  def self.find_url(slug)
    id = decode_slug(slug)
    short_url = find(id)
    short_url.url
  end

  private

  def self.decode_slug(slug)
    slug.to_i(36)
  end

  def encode_slug
    id.to_s(36)
  end

  def prepend_http
    self.url = "http://#{self.url}" unless url_begins_with_http?
  end

  def url_begins_with_http?
    url.index("http") == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  def show
    url = ShortUrl.find_url(params[:slug])

    redirect_to url
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  def new
    @short_url = ShortUrl.new
  end

  def create
    @short_url = ShortUrl.create(short_url_params)

    if @short_url.save
      redirect_to @short_url
    else
      render :new
    end
  end

  def show
    short_url = ShortUrl.find(params[:id])
    @redirect_url = short_url.shorten
  end

  private

  def short_url_params
    params.
      require(:short_url).
      permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TurboBear</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/short_urls/new.html.erb
<%= form_for @short_url do |form| %>
  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>
  <%= form.submit "Shorten!" %>
<% end %>

app/views/short_urls/show.html.erb
<%= link_to "New Short URL", new_short_url_path %><br>
<%= link_to @redirect_url, @redirect_url %>